### PR TITLE
fixed main page login bug

### PR DESCRIPTION
**Pull request by yasintz**

### CODE REVIEW

**Comment by yakuter** [comment]
There is a conflict :/

**Comment by yasintz** [comment]
@yakuter

**Comment by yakuter** [comment]
Thank you.

**Comment by yakuter** [comment]
Screen Shot 2020-04-24 at 16 42 30

**Comment by yasintz** [comment]
> @yasintz there is error
> Screen Shot 2020-04-24 at 16 42 30

sorry. It must have happened during the conflict. I'm fixing now.

**Pull request merged**
