### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by cyberst**
Added the Logo to Login Page, Header and Favicon. 
Made the Favicon background transparent.
Made the Favicon compatible with different platforms from the site https://realfavicongenerator.net/
Changed the Readme with new SS that has Logo.
#4 

ss1
ss2

### CODE REVIEW

**Comment by yakuter** [comment]
Hello @cyberst thanks for great job. Can you change the logo images with the originals I am sending below. Then I will merge the PR. Thank you.

https://www.yakuter.com/wp-content/yuklemeler/PassWall-Logos.zip

**Comment by cyberst** [comment]
Hello @yakuter. Thank you for your great comments. I wasn't aware of the original logo images. I added them logo images now :)

**Comment by yakuter** [comment]
Thank you for your contribution @cyberst

**Comment by safakkizkin** [comment]
Hi there,
FYI, the logos, using in this PR, have background color. A change may be good in there.
as an example, 
image

**Comment by cyberst** [comment]
Hi @safakkizkin,
Thank you for pointing out. I think we should remove the background color too. 

@yakuter What do you think? If you think this is necessary as well, shall I remove the background color from the images or would you like to do it, maybe for all pass-wall repositories?

**Pull request merged**
